# Generated by Django 5.1 on 2024-08-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conferences',
        ),
        migrations.DeleteModel(
            name='Eventorganized',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='FoundedProject',
        ),
        migrations.DeleteModel(
            name='InvitedTalks',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Seminars',
        ),
        migrations.DeleteModel(
            name='Subject_experience',
        ),
    ]
