# Generated by Django 5.1 on 2024-08-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_content', models.CharField(blank=True, max_length=500)),
                ('color_text', models.CharField(blank=True, max_length=500)),
                ('end_content', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
