# Generated by Django 5.1 on 2024-08-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_foundedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_content', models.CharField(blank=True, max_length=500)),
                ('color_text', models.CharField(blank=True, max_length=500)),
                ('end_content', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Eventorganized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_content', models.CharField(blank=True, max_length=500)),
                ('color_text', models.CharField(blank=True, max_length=500)),
                ('end_content', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedTalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_content', models.CharField(blank=True, max_length=500)),
                ('color_text', models.CharField(blank=True, max_length=500)),
                ('end_content', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_content', models.CharField(blank=True, max_length=500)),
                ('color_text', models.CharField(blank=True, max_length=500)),
                ('end_content', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
