# Generated by Django 5.1 on 2024-08-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_conferences_eventorganized_invitedtalks_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table='Portfolio_table',
        ),
    ]
