# Generated by Django 5.1 on 2024-08-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_images_image_alter_images_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
